[profile.release]
opt-level = 3
debug = true
lto = 'thin'
panic = 'abort'

[workspace]
members = [
    'advent',
    'advent_macro',
    'five',
    'four',
    'one',
    'parse',
    'parse_macro',
    'seven',
    'six',
    'three',
    'two',
]
