[package]
name = "fifteen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
range-collections = "0.2.4"
advent = { path = "../advent" }
parse = { path = "../parse" }
combine = "*"
